# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-10 10:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='reviews',
            field=models.CharField(default=datetime.datetime(2017, 4, 10, 10, 47, 33, 317306, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
    ]
