# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-10 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='reviews',
        ),
    ]
