# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-11 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='favourite',
            new_name='is_favourite',
        ),
    ]
